export namespace Selectors {
  export const SIGN_IN_TEXT = 'Sign in'
  export const ALLOW_ALL = '[data-test=allow-all]'
  export const SERACH_PRODUCT = '#desktopSearch'
  export const PRODUCT_LINE_HEADING = '[data-test="heading-term"]'
  export const PRODUCT_TITLE_HEADING = '[data-test="product-title"] h2'
  export const PRODUCT_UNIT_PRICE = '.price_c-product-card__price__3NI9k'
  export const PRODUCT_PAGE_HEADING = '#confirmation-anchor-desktop'
  export const ADD_TO_BASKET_BUTTON = '[data-cy="add-to-basket-button"]'
  export const BASKET_CONFIRMATION_BUTTON = '[data-cy="basket-confirmation"]'
  export const BUTTON = 'button'
  export const QTY_FIELD = '.quantity-input'
  export const BASKET_LIST_PRICE = '.basket-list-price'
  export const QTY_DECREASE_BUTTON = '.quantity-decrease-button'
}
